/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PortalOverviewIndexRouteImport } from './routes/portal/overview/index'
import { Route as PortalModalsIndexRouteImport } from './routes/portal/modals/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs/index'
import { Route as AdminCronjobsIndexRouteImport } from './routes/admin/cronjobs/index'
import { Route as PortalUsersNameRouteImport } from './routes/portal/users/$name'
import { Route as PortalOverviewNodeRouteImport } from './routes/portal/overview/$node'
import { Route as PortalMonitorNetworkRouteImport } from './routes/portal/monitor/network'
import { Route as PortalMonitorIdleRouteImport } from './routes/portal/monitor/idle'
import { Route as PortalMonitorGpuRouteImport } from './routes/portal/monitor/gpu'
import { Route as IngressJupyterNameRouteImport } from './routes/ingress/jupyter.$name'
import { Route as AdminUsersNameRouteImport } from './routes/admin/users/$name'
import { Route as AdminMonitorNetworkRouteImport } from './routes/admin/monitor/network'
import { Route as AdminMonitorIdleRouteImport } from './routes/admin/monitor/idle'
import { Route as AdminMonitorGpuRouteImport } from './routes/admin/monitor/gpu'
import { Route as AdminJobsNameRouteImport } from './routes/admin/jobs/$name'
import { Route as PortalJobsInterIndexRouteImport } from './routes/portal/jobs/inter/index'
import { Route as PortalJobsCustomIndexRouteImport } from './routes/portal/jobs/custom/index'
import { Route as AdminClusterResourcesIndexRouteImport } from './routes/admin/cluster/resources/index'
import { Route as AdminClusterNodesIndexRouteImport } from './routes/admin/cluster/nodes/index'
import { Route as PortalJobsCustomNewVolcanoJobRouteImport } from './routes/portal/jobs/custom/new/volcano-job'
import { Route as PortalJobsCustomNewTensorflowPsJobRouteImport } from './routes/portal/jobs/custom/new/tensorflow-ps-job'
import { Route as PortalJobsCustomNewSeacsJobRouteImport } from './routes/portal/jobs/custom/new/seacs-job'
import { Route as PortalJobsCustomNewPytorchDdpJobRouteImport } from './routes/portal/jobs/custom/new/pytorch-ddp-job'
import { Route as PortalJobsCustomNewEmiasJobRouteImport } from './routes/portal/jobs/custom/new/emias-job'
import { Route as PortalJobsCustomDetailNameRouteImport } from './routes/portal/jobs/custom/detail.$name'

const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalOverviewIndexRoute = PortalOverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalModalsIndexRoute = PortalModalsIndexRouteImport.update({
  id: '/modals/',
  path: '/modals/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCronjobsIndexRoute = AdminCronjobsIndexRouteImport.update({
  id: '/cronjobs/',
  path: '/cronjobs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalUsersNameRoute = PortalUsersNameRouteImport.update({
  id: '/users/$name',
  path: '/users/$name',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalOverviewNodeRoute = PortalOverviewNodeRouteImport.update({
  id: '/overview/$node',
  path: '/overview/$node',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalMonitorNetworkRoute = PortalMonitorNetworkRouteImport.update({
  id: '/monitor/network',
  path: '/monitor/network',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalMonitorIdleRoute = PortalMonitorIdleRouteImport.update({
  id: '/monitor/idle',
  path: '/monitor/idle',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalMonitorGpuRoute = PortalMonitorGpuRouteImport.update({
  id: '/monitor/gpu',
  path: '/monitor/gpu',
  getParentRoute: () => PortalRouteRoute,
} as any)
const IngressJupyterNameRoute = IngressJupyterNameRouteImport.update({
  id: '/ingress/jupyter/$name',
  path: '/ingress/jupyter/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersNameRoute = AdminUsersNameRouteImport.update({
  id: '/users/$name',
  path: '/users/$name',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMonitorNetworkRoute = AdminMonitorNetworkRouteImport.update({
  id: '/monitor/network',
  path: '/monitor/network',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMonitorIdleRoute = AdminMonitorIdleRouteImport.update({
  id: '/monitor/idle',
  path: '/monitor/idle',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMonitorGpuRoute = AdminMonitorGpuRouteImport.update({
  id: '/monitor/gpu',
  path: '/monitor/gpu',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsNameRoute = AdminJobsNameRouteImport.update({
  id: '/jobs/$name',
  path: '/jobs/$name',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalJobsInterIndexRoute = PortalJobsInterIndexRouteImport.update({
  id: '/jobs/inter/',
  path: '/jobs/inter/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalJobsCustomIndexRoute = PortalJobsCustomIndexRouteImport.update({
  id: '/jobs/custom/',
  path: '/jobs/custom/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const AdminClusterResourcesIndexRoute =
  AdminClusterResourcesIndexRouteImport.update({
    id: '/cluster/resources/',
    path: '/cluster/resources/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminClusterNodesIndexRoute = AdminClusterNodesIndexRouteImport.update({
  id: '/cluster/nodes/',
  path: '/cluster/nodes/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PortalJobsCustomNewVolcanoJobRoute =
  PortalJobsCustomNewVolcanoJobRouteImport.update({
    id: '/jobs/custom/new/volcano-job',
    path: '/jobs/custom/new/volcano-job',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalJobsCustomNewTensorflowPsJobRoute =
  PortalJobsCustomNewTensorflowPsJobRouteImport.update({
    id: '/jobs/custom/new/tensorflow-ps-job',
    path: '/jobs/custom/new/tensorflow-ps-job',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalJobsCustomNewSeacsJobRoute =
  PortalJobsCustomNewSeacsJobRouteImport.update({
    id: '/jobs/custom/new/seacs-job',
    path: '/jobs/custom/new/seacs-job',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalJobsCustomNewPytorchDdpJobRoute =
  PortalJobsCustomNewPytorchDdpJobRouteImport.update({
    id: '/jobs/custom/new/pytorch-ddp-job',
    path: '/jobs/custom/new/pytorch-ddp-job',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalJobsCustomNewEmiasJobRoute =
  PortalJobsCustomNewEmiasJobRouteImport.update({
    id: '/jobs/custom/new/emias-job',
    path: '/jobs/custom/new/emias-job',
    getParentRoute: () => PortalRouteRoute,
  } as any)
const PortalJobsCustomDetailNameRoute =
  PortalJobsCustomDetailNameRouteImport.update({
    id: '/jobs/custom/detail/$name',
    path: '/jobs/custom/detail/$name',
    getParentRoute: () => PortalRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/jobs/$name': typeof AdminJobsNameRoute
  '/admin/monitor/gpu': typeof AdminMonitorGpuRoute
  '/admin/monitor/idle': typeof AdminMonitorIdleRoute
  '/admin/monitor/network': typeof AdminMonitorNetworkRoute
  '/admin/users/$name': typeof AdminUsersNameRoute
  '/ingress/jupyter/$name': typeof IngressJupyterNameRoute
  '/portal/monitor/gpu': typeof PortalMonitorGpuRoute
  '/portal/monitor/idle': typeof PortalMonitorIdleRoute
  '/portal/monitor/network': typeof PortalMonitorNetworkRoute
  '/portal/overview/$node': typeof PortalOverviewNodeRoute
  '/portal/users/$name': typeof PortalUsersNameRoute
  '/admin/cronjobs': typeof AdminCronjobsIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/portal/modals': typeof PortalModalsIndexRoute
  '/portal/overview': typeof PortalOverviewIndexRoute
  '/admin/cluster/nodes': typeof AdminClusterNodesIndexRoute
  '/admin/cluster/resources': typeof AdminClusterResourcesIndexRoute
  '/portal/jobs/custom': typeof PortalJobsCustomIndexRoute
  '/portal/jobs/inter': typeof PortalJobsInterIndexRoute
  '/portal/jobs/custom/detail/$name': typeof PortalJobsCustomDetailNameRoute
  '/portal/jobs/custom/new/emias-job': typeof PortalJobsCustomNewEmiasJobRoute
  '/portal/jobs/custom/new/pytorch-ddp-job': typeof PortalJobsCustomNewPytorchDdpJobRoute
  '/portal/jobs/custom/new/seacs-job': typeof PortalJobsCustomNewSeacsJobRoute
  '/portal/jobs/custom/new/tensorflow-ps-job': typeof PortalJobsCustomNewTensorflowPsJobRoute
  '/portal/jobs/custom/new/volcano-job': typeof PortalJobsCustomNewVolcanoJobRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/jobs/$name': typeof AdminJobsNameRoute
  '/admin/monitor/gpu': typeof AdminMonitorGpuRoute
  '/admin/monitor/idle': typeof AdminMonitorIdleRoute
  '/admin/monitor/network': typeof AdminMonitorNetworkRoute
  '/admin/users/$name': typeof AdminUsersNameRoute
  '/ingress/jupyter/$name': typeof IngressJupyterNameRoute
  '/portal/monitor/gpu': typeof PortalMonitorGpuRoute
  '/portal/monitor/idle': typeof PortalMonitorIdleRoute
  '/portal/monitor/network': typeof PortalMonitorNetworkRoute
  '/portal/overview/$node': typeof PortalOverviewNodeRoute
  '/portal/users/$name': typeof PortalUsersNameRoute
  '/admin/cronjobs': typeof AdminCronjobsIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/portal/modals': typeof PortalModalsIndexRoute
  '/portal/overview': typeof PortalOverviewIndexRoute
  '/admin/cluster/nodes': typeof AdminClusterNodesIndexRoute
  '/admin/cluster/resources': typeof AdminClusterResourcesIndexRoute
  '/portal/jobs/custom': typeof PortalJobsCustomIndexRoute
  '/portal/jobs/inter': typeof PortalJobsInterIndexRoute
  '/portal/jobs/custom/detail/$name': typeof PortalJobsCustomDetailNameRoute
  '/portal/jobs/custom/new/emias-job': typeof PortalJobsCustomNewEmiasJobRoute
  '/portal/jobs/custom/new/pytorch-ddp-job': typeof PortalJobsCustomNewPytorchDdpJobRoute
  '/portal/jobs/custom/new/seacs-job': typeof PortalJobsCustomNewSeacsJobRoute
  '/portal/jobs/custom/new/tensorflow-ps-job': typeof PortalJobsCustomNewTensorflowPsJobRoute
  '/portal/jobs/custom/new/volcano-job': typeof PortalJobsCustomNewVolcanoJobRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/jobs/$name': typeof AdminJobsNameRoute
  '/admin/monitor/gpu': typeof AdminMonitorGpuRoute
  '/admin/monitor/idle': typeof AdminMonitorIdleRoute
  '/admin/monitor/network': typeof AdminMonitorNetworkRoute
  '/admin/users/$name': typeof AdminUsersNameRoute
  '/ingress/jupyter/$name': typeof IngressJupyterNameRoute
  '/portal/monitor/gpu': typeof PortalMonitorGpuRoute
  '/portal/monitor/idle': typeof PortalMonitorIdleRoute
  '/portal/monitor/network': typeof PortalMonitorNetworkRoute
  '/portal/overview/$node': typeof PortalOverviewNodeRoute
  '/portal/users/$name': typeof PortalUsersNameRoute
  '/admin/cronjobs/': typeof AdminCronjobsIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/portal/modals/': typeof PortalModalsIndexRoute
  '/portal/overview/': typeof PortalOverviewIndexRoute
  '/admin/cluster/nodes/': typeof AdminClusterNodesIndexRoute
  '/admin/cluster/resources/': typeof AdminClusterResourcesIndexRoute
  '/portal/jobs/custom/': typeof PortalJobsCustomIndexRoute
  '/portal/jobs/inter/': typeof PortalJobsInterIndexRoute
  '/portal/jobs/custom/detail/$name': typeof PortalJobsCustomDetailNameRoute
  '/portal/jobs/custom/new/emias-job': typeof PortalJobsCustomNewEmiasJobRoute
  '/portal/jobs/custom/new/pytorch-ddp-job': typeof PortalJobsCustomNewPytorchDdpJobRoute
  '/portal/jobs/custom/new/seacs-job': typeof PortalJobsCustomNewSeacsJobRoute
  '/portal/jobs/custom/new/tensorflow-ps-job': typeof PortalJobsCustomNewTensorflowPsJobRoute
  '/portal/jobs/custom/new/volcano-job': typeof PortalJobsCustomNewVolcanoJobRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/portal'
    | '/admin/'
    | '/auth'
    | '/portal/'
    | '/admin/jobs/$name'
    | '/admin/monitor/gpu'
    | '/admin/monitor/idle'
    | '/admin/monitor/network'
    | '/admin/users/$name'
    | '/ingress/jupyter/$name'
    | '/portal/monitor/gpu'
    | '/portal/monitor/idle'
    | '/portal/monitor/network'
    | '/portal/overview/$node'
    | '/portal/users/$name'
    | '/admin/cronjobs'
    | '/admin/jobs'
    | '/admin/users'
    | '/portal/modals'
    | '/portal/overview'
    | '/admin/cluster/nodes'
    | '/admin/cluster/resources'
    | '/portal/jobs/custom'
    | '/portal/jobs/inter'
    | '/portal/jobs/custom/detail/$name'
    | '/portal/jobs/custom/new/emias-job'
    | '/portal/jobs/custom/new/pytorch-ddp-job'
    | '/portal/jobs/custom/new/seacs-job'
    | '/portal/jobs/custom/new/tensorflow-ps-job'
    | '/portal/jobs/custom/new/volcano-job'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/portal'
    | '/admin/jobs/$name'
    | '/admin/monitor/gpu'
    | '/admin/monitor/idle'
    | '/admin/monitor/network'
    | '/admin/users/$name'
    | '/ingress/jupyter/$name'
    | '/portal/monitor/gpu'
    | '/portal/monitor/idle'
    | '/portal/monitor/network'
    | '/portal/overview/$node'
    | '/portal/users/$name'
    | '/admin/cronjobs'
    | '/admin/jobs'
    | '/admin/users'
    | '/portal/modals'
    | '/portal/overview'
    | '/admin/cluster/nodes'
    | '/admin/cluster/resources'
    | '/portal/jobs/custom'
    | '/portal/jobs/inter'
    | '/portal/jobs/custom/detail/$name'
    | '/portal/jobs/custom/new/emias-job'
    | '/portal/jobs/custom/new/pytorch-ddp-job'
    | '/portal/jobs/custom/new/seacs-job'
    | '/portal/jobs/custom/new/tensorflow-ps-job'
    | '/portal/jobs/custom/new/volcano-job'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/portal'
    | '/admin/'
    | '/auth/'
    | '/portal/'
    | '/admin/jobs/$name'
    | '/admin/monitor/gpu'
    | '/admin/monitor/idle'
    | '/admin/monitor/network'
    | '/admin/users/$name'
    | '/ingress/jupyter/$name'
    | '/portal/monitor/gpu'
    | '/portal/monitor/idle'
    | '/portal/monitor/network'
    | '/portal/overview/$node'
    | '/portal/users/$name'
    | '/admin/cronjobs/'
    | '/admin/jobs/'
    | '/admin/users/'
    | '/portal/modals/'
    | '/portal/overview/'
    | '/admin/cluster/nodes/'
    | '/admin/cluster/resources/'
    | '/portal/jobs/custom/'
    | '/portal/jobs/inter/'
    | '/portal/jobs/custom/detail/$name'
    | '/portal/jobs/custom/new/emias-job'
    | '/portal/jobs/custom/new/pytorch-ddp-job'
    | '/portal/jobs/custom/new/seacs-job'
    | '/portal/jobs/custom/new/tensorflow-ps-job'
    | '/portal/jobs/custom/new/volcano-job'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  IngressJupyterNameRoute: typeof IngressJupyterNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/portal/overview/': {
      id: '/portal/overview/'
      path: '/overview'
      fullPath: '/portal/overview'
      preLoaderRoute: typeof PortalOverviewIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/modals/': {
      id: '/portal/modals/'
      path: '/modals'
      fullPath: '/portal/modals'
      preLoaderRoute: typeof PortalModalsIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cronjobs/': {
      id: '/admin/cronjobs/'
      path: '/cronjobs'
      fullPath: '/admin/cronjobs'
      preLoaderRoute: typeof AdminCronjobsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/portal/users/$name': {
      id: '/portal/users/$name'
      path: '/users/$name'
      fullPath: '/portal/users/$name'
      preLoaderRoute: typeof PortalUsersNameRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/overview/$node': {
      id: '/portal/overview/$node'
      path: '/overview/$node'
      fullPath: '/portal/overview/$node'
      preLoaderRoute: typeof PortalOverviewNodeRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/monitor/network': {
      id: '/portal/monitor/network'
      path: '/monitor/network'
      fullPath: '/portal/monitor/network'
      preLoaderRoute: typeof PortalMonitorNetworkRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/monitor/idle': {
      id: '/portal/monitor/idle'
      path: '/monitor/idle'
      fullPath: '/portal/monitor/idle'
      preLoaderRoute: typeof PortalMonitorIdleRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/monitor/gpu': {
      id: '/portal/monitor/gpu'
      path: '/monitor/gpu'
      fullPath: '/portal/monitor/gpu'
      preLoaderRoute: typeof PortalMonitorGpuRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/ingress/jupyter/$name': {
      id: '/ingress/jupyter/$name'
      path: '/ingress/jupyter/$name'
      fullPath: '/ingress/jupyter/$name'
      preLoaderRoute: typeof IngressJupyterNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$name': {
      id: '/admin/users/$name'
      path: '/users/$name'
      fullPath: '/admin/users/$name'
      preLoaderRoute: typeof AdminUsersNameRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/monitor/network': {
      id: '/admin/monitor/network'
      path: '/monitor/network'
      fullPath: '/admin/monitor/network'
      preLoaderRoute: typeof AdminMonitorNetworkRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/monitor/idle': {
      id: '/admin/monitor/idle'
      path: '/monitor/idle'
      fullPath: '/admin/monitor/idle'
      preLoaderRoute: typeof AdminMonitorIdleRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/monitor/gpu': {
      id: '/admin/monitor/gpu'
      path: '/monitor/gpu'
      fullPath: '/admin/monitor/gpu'
      preLoaderRoute: typeof AdminMonitorGpuRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs/$name': {
      id: '/admin/jobs/$name'
      path: '/jobs/$name'
      fullPath: '/admin/jobs/$name'
      preLoaderRoute: typeof AdminJobsNameRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/portal/jobs/inter/': {
      id: '/portal/jobs/inter/'
      path: '/jobs/inter'
      fullPath: '/portal/jobs/inter'
      preLoaderRoute: typeof PortalJobsInterIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/jobs/custom/': {
      id: '/portal/jobs/custom/'
      path: '/jobs/custom'
      fullPath: '/portal/jobs/custom'
      preLoaderRoute: typeof PortalJobsCustomIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/admin/cluster/resources/': {
      id: '/admin/cluster/resources/'
      path: '/cluster/resources'
      fullPath: '/admin/cluster/resources'
      preLoaderRoute: typeof AdminClusterResourcesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cluster/nodes/': {
      id: '/admin/cluster/nodes/'
      path: '/cluster/nodes'
      fullPath: '/admin/cluster/nodes'
      preLoaderRoute: typeof AdminClusterNodesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/portal/jobs/custom/new/volcano-job': {
      id: '/portal/jobs/custom/new/volcano-job'
      path: '/jobs/custom/new/volcano-job'
      fullPath: '/portal/jobs/custom/new/volcano-job'
      preLoaderRoute: typeof PortalJobsCustomNewVolcanoJobRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/jobs/custom/new/tensorflow-ps-job': {
      id: '/portal/jobs/custom/new/tensorflow-ps-job'
      path: '/jobs/custom/new/tensorflow-ps-job'
      fullPath: '/portal/jobs/custom/new/tensorflow-ps-job'
      preLoaderRoute: typeof PortalJobsCustomNewTensorflowPsJobRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/jobs/custom/new/seacs-job': {
      id: '/portal/jobs/custom/new/seacs-job'
      path: '/jobs/custom/new/seacs-job'
      fullPath: '/portal/jobs/custom/new/seacs-job'
      preLoaderRoute: typeof PortalJobsCustomNewSeacsJobRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/jobs/custom/new/pytorch-ddp-job': {
      id: '/portal/jobs/custom/new/pytorch-ddp-job'
      path: '/jobs/custom/new/pytorch-ddp-job'
      fullPath: '/portal/jobs/custom/new/pytorch-ddp-job'
      preLoaderRoute: typeof PortalJobsCustomNewPytorchDdpJobRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/jobs/custom/new/emias-job': {
      id: '/portal/jobs/custom/new/emias-job'
      path: '/jobs/custom/new/emias-job'
      fullPath: '/portal/jobs/custom/new/emias-job'
      preLoaderRoute: typeof PortalJobsCustomNewEmiasJobRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/jobs/custom/detail/$name': {
      id: '/portal/jobs/custom/detail/$name'
      path: '/jobs/custom/detail/$name'
      fullPath: '/portal/jobs/custom/detail/$name'
      preLoaderRoute: typeof PortalJobsCustomDetailNameRouteImport
      parentRoute: typeof PortalRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminJobsNameRoute: typeof AdminJobsNameRoute
  AdminMonitorGpuRoute: typeof AdminMonitorGpuRoute
  AdminMonitorIdleRoute: typeof AdminMonitorIdleRoute
  AdminMonitorNetworkRoute: typeof AdminMonitorNetworkRoute
  AdminUsersNameRoute: typeof AdminUsersNameRoute
  AdminCronjobsIndexRoute: typeof AdminCronjobsIndexRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminClusterNodesIndexRoute: typeof AdminClusterNodesIndexRoute
  AdminClusterResourcesIndexRoute: typeof AdminClusterResourcesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminJobsNameRoute: AdminJobsNameRoute,
  AdminMonitorGpuRoute: AdminMonitorGpuRoute,
  AdminMonitorIdleRoute: AdminMonitorIdleRoute,
  AdminMonitorNetworkRoute: AdminMonitorNetworkRoute,
  AdminUsersNameRoute: AdminUsersNameRoute,
  AdminCronjobsIndexRoute: AdminCronjobsIndexRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminClusterNodesIndexRoute: AdminClusterNodesIndexRoute,
  AdminClusterResourcesIndexRoute: AdminClusterResourcesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalIndexRoute: typeof PortalIndexRoute
  PortalMonitorGpuRoute: typeof PortalMonitorGpuRoute
  PortalMonitorIdleRoute: typeof PortalMonitorIdleRoute
  PortalMonitorNetworkRoute: typeof PortalMonitorNetworkRoute
  PortalOverviewNodeRoute: typeof PortalOverviewNodeRoute
  PortalUsersNameRoute: typeof PortalUsersNameRoute
  PortalModalsIndexRoute: typeof PortalModalsIndexRoute
  PortalOverviewIndexRoute: typeof PortalOverviewIndexRoute
  PortalJobsCustomIndexRoute: typeof PortalJobsCustomIndexRoute
  PortalJobsInterIndexRoute: typeof PortalJobsInterIndexRoute
  PortalJobsCustomDetailNameRoute: typeof PortalJobsCustomDetailNameRoute
  PortalJobsCustomNewEmiasJobRoute: typeof PortalJobsCustomNewEmiasJobRoute
  PortalJobsCustomNewPytorchDdpJobRoute: typeof PortalJobsCustomNewPytorchDdpJobRoute
  PortalJobsCustomNewSeacsJobRoute: typeof PortalJobsCustomNewSeacsJobRoute
  PortalJobsCustomNewTensorflowPsJobRoute: typeof PortalJobsCustomNewTensorflowPsJobRoute
  PortalJobsCustomNewVolcanoJobRoute: typeof PortalJobsCustomNewVolcanoJobRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalIndexRoute: PortalIndexRoute,
  PortalMonitorGpuRoute: PortalMonitorGpuRoute,
  PortalMonitorIdleRoute: PortalMonitorIdleRoute,
  PortalMonitorNetworkRoute: PortalMonitorNetworkRoute,
  PortalOverviewNodeRoute: PortalOverviewNodeRoute,
  PortalUsersNameRoute: PortalUsersNameRoute,
  PortalModalsIndexRoute: PortalModalsIndexRoute,
  PortalOverviewIndexRoute: PortalOverviewIndexRoute,
  PortalJobsCustomIndexRoute: PortalJobsCustomIndexRoute,
  PortalJobsInterIndexRoute: PortalJobsInterIndexRoute,
  PortalJobsCustomDetailNameRoute: PortalJobsCustomDetailNameRoute,
  PortalJobsCustomNewEmiasJobRoute: PortalJobsCustomNewEmiasJobRoute,
  PortalJobsCustomNewPytorchDdpJobRoute: PortalJobsCustomNewPytorchDdpJobRoute,
  PortalJobsCustomNewSeacsJobRoute: PortalJobsCustomNewSeacsJobRoute,
  PortalJobsCustomNewTensorflowPsJobRoute:
    PortalJobsCustomNewTensorflowPsJobRoute,
  PortalJobsCustomNewVolcanoJobRoute: PortalJobsCustomNewVolcanoJobRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  IngressJupyterNameRoute: IngressJupyterNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
